
services:
  db:
    image: postgres
    container_name: jwt_postgres
    restart: always
    ports:
      - "54321:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: jwt_auth
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
